package com.khatep.enums;

public enum Majors {
    INFORMATION_SYSTEMS, SOFTWARE_ENGINEERING, COMPUTER_SCIENCE, DATA_SCIENCE, COMPUTER_SECURITY,
    MANAGEMENT, FINANCE_MANAGEMENT, DIGITAL_JOURNALISM, UNKNOWN;
}
